### ISSUE TITLE
Improve (startup) performance

### ISSUE THREAD

**Issue by koenbok** [framer/monobase#37]
- [x] Add a layer of caching
- [x] Upgrade Webpack
- [x] See if we can just rebuild user code (keep libraries external)

**Comment by aron** [comment]
How about we just lean on Webpack entirely as the build system, it already provides a dev server and watcher and can output a static build. We'd just need to generate the config based on the directory structure. Webpack will then just rebuild the code that changes.

**Comment by koenbok** [comment]
I'd be happy to research that but it's one of those cases where I think that's where I started and then went here for good reasons that I can't remember :-)

We can at least do it partly through relying on webpack watchers and fix a bunch of stuff.
