### ISSUE TITLE
Styled component loses all styling when using props to style

### ISSUE THREAD

**Issue by fverloop** [framer/monobase#39]
Consider this example:

```jsx
import { Dynamic } from "monobase"
import * as React from "react"
import styled from "styled-components"

const Button = styled.button<{ error: boolean }>`
  background: ${props => (props.error ? "#F44" : "#09F")};
  border-radius: 4px;
  border: none;
  color: #FFF;
  font-size: 1em;
  margin: 1em;
  outline: 0;
  padding: 0.25em 1em;
`

class Styled extends React.Component<{}, { error: boolean }> {
  state = { error: false }

  handleClick = () => {
    this.setState({ error: !this.state.error })
  }

  render() {
    return (
      <Button onClick={this.handleClick} error={this.state.error}>
        Button
      </Button>
    )
  }
}

export default Dynamic(Styled)
```

Using props to change styles is common in Styled Components. However, when using this approach in Monobase, the component loses all styling after changing the prop:

![style](https://user-images.githubusercontent.com/1180195/52554241-762e8900-2de6-11e9-96d7-e6267c79fa61.gif)

It does change the classname after changing the prop, but there's no styling attached to it:

![classname](https://user-images.githubusercontent.com/1180195/52554448-29977d80-2de7-11e9-9aaa-7f50ffbe8e09.gif)

**Comment by koenbok** [comment]
Fixed in https://github.com/framer/monobase/commit/e6ae760680612ea1458d6dfc4697e45ae8fc3557
