### ISSUE TITLE
Wrapping component element breaks parent/child relations

### ISSUE THREAD

**Issue by fverloop** [framer/monobase#42]
I have a parent → child relation setup where the parent has `display: grid` enabled and the child has `grid-column: auto/span 2` to span 2 columns. When using a `Dynamic` component as a child, that relationship breaks because the child is wrapped in a `<component />` element.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1180195/53719091-64785880-3e5d-11e9-8902-ffde9bd4499d.png">

Is there a way `Dynamic` components can be rendered without that wrapping element?

**Comment by aron** [comment]
Was looking into this yesterday, I think we should be able to do this by adding the data attribute to the element wrapped with `Dynamic`, then client side just wrapping it in a temporary parent div for the hydration then removing it again.

**Comment by fverloop** [comment]
Wouldn't it then temporarily break the layout while using a wrapping element for hydration?

**Comment by aron** [comment]
Yes, but you'd not see it. The problem is that hydrate requires you to provide a parent node and _all_ of the children. So we need to ensure that Dynamic components have a parent with the component as the only child. Hence the `<component>` wrapper.
