### ISSUE TITLE
Port keeps increasing

### ISSUE THREAD

**Issue by fverloop** [framer/monobase#44]
It seems that, as long as I don't reboot my machine, Monobase keeps bumping the port number. I'm at `1259` now. For testing purposes, it would be great if I could predict what port Monobase will run on, maybe even a fixed port via an option flag.

![image](https://user-images.githubusercontent.com/1180195/53871348-6298cb80-3ffc-11e9-81b6-98ed3f9e88da.png)

**Comment by koenbok** [comment]
This still true @fverloop?
